require('user.plugin_config.lualine')
require('user.plugin_config.nvim_tree')
require('user.plugin_config.copilot')
require('user.plugin_config.colorscheme')
require('user.plugin_config.telescope')
require('user.plugin_config.treesitter')
require('user.plugin_config.bufferline')
require('user.plugin_config.lsp')
require('user.plugin_config.gitsigns')
require('user.plugin_config.whichkey')
require('user.plugin_config.alpha')
require('user.plugin_config.autopairs')
-- require('user.plugin_config.cmp')
require('user.plugin_config.impatient')
